# Generated by Django 5.0 on 2023-12-05 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_prof_id', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_stud_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assign_id', models.IntegerField()),
                ('grade', models.IntegerField()),
                ('description', models.CharField(max_length=512)),
                ('feedback', models.CharField(max_length=512)),
                ('file', models.FileField(upload_to='')),
                ('date_of_submission', models.DateTimeField()),
                ('pending', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course', related_name='assign_course_id')),
            ],
        ),
    ]
