# Generated by Django 5.0 on 2023-12-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='feedback',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='finished',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
