# Generated by Django 5.0 on 2023-12-05 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_assignment_feedback_alter_assignment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='prof',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assign_prof_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assign_stud_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
