# Generated by Django 5.0 on 2023-12-05 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_assignment_prof_assignment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='prof',
            new_name='assign_prof',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='student',
            new_name='assign_student',
        ),
    ]
